import type { Metadata } from "next";
import "./globals.css";
import 'leaflet/dist/leaflet.css';
import LeftSidebar from "@/components/LeftSidebar";
import { getUserData } from "@/actions/get-user-data";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
  title: "City Chain",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserData();

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-poppins">
        <div className="w-full h-full flex justify-center items-center relative text-black font-poppins">
          <div className="px-16 w-full h-full flex relative">

            {user && <LeftSidebar />}
            {children}

          </div>
        </div>
      </body>
    </html>
  );
}